version: '3'

services:
  deno-rest:
    build: .
    image: deno-rest
    ports:
      - '9000:9000'
    depends_on:
      - mongo
    restart: on-failure
    container_name: 'deno-rest'
    networks:
      - network
    logging:
      options:
        max-size: '5k'

  mongo:
    image: mongo:latest
    restart: always
    healthcheck:
      test: ['CMD-SHELL', "echo 'db.runCommand({ping: 1}).ok' | mongo --quiet"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - '27017:27017'
    container_name: 'mongo_db_server'
    volumes:
      - mongo_data:/data/db
    networks:
      - network
    logging:
      options:
        max-size: '5k'

volumes:
  mongo_data:

networks:
  network:
    driver: bridge
